name: Keep docs sync

on:
  push:
    branches:
      - gh-pages

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ“¦ Setup node and pnpm install
        uses: ./.github/share-actions/setup-node-and-pnpm-install

      - name: ğŸ”§ Run generation
        run: pnpm run-all

        # there is no push if no diff
      - name: ğŸš€ Push API reference documentation
        uses: ./.github/share-actions/commit-and-push-docs
